### PR TITLE
Refactoring quest stuff

### PR DESCRIPTION
**Pull request by Azn2000**
# Changes DialogCompleter
Refactored DialogCompleter => Constructor
Added Path Support for DialogCompleter (For more supported situations, example: Romeo and Juliet)
Added ForcedWalkType for DialogCompleter (not really happy with this solution)

# Implemented DialogCompleter
 On Romeo & Juliet
 On Cooks Assistant
 On Sheep Shearer

# New ItemCompleter
Same as DialogCompleter => I saw alot of different implementations of GetItemFromGround or GetItemFromObject. Now all in one class.
Supports ground items / items from objects and items from simple npcs (without dialog)

# Implemented ItemCompleter
 On Romeo & Juliet
 On Cooks Assistant
 On Sheep Shearer

# Fix on Romeo & Juliet

#39 is implement now with the new DialogCompleter

### CODE REVIEW

**Comment by Azn2000** [comment]
Oh boi, i'm scarred of your reviews 😢 😆

**Comment by Azn2000** [comment]
These logs never meant to be int the repository anyway lol
Forgot about them when i was looking for a bug 🙈 
Well, now where they are in place I will them make a lot more descriptive

**Comment by Azn2000** [comment]
Ok the logging is now improved, now including also information for us

**Comment by Azn2000** [comment]
Well, it worked: Now im getting a lot of wierd behavior when im doing the quests.

Because we are not looking for the area anymore, the bot tries to interact with sheeps for example but moves against a wall.

I need to fix this stuff first :(

**Comment by Azn2000** [comment]
@MasterOfHash @RealPoke @Explv 
I know a weird place to ask this for but what do you guys think about a discord channel where we could discuss stuff?

**Comment by MasterOfHash** [comment]
I don’t use discord but I’d be down to make a slack room or something.

**Comment by MasterOfHash** [comment]
I don't use discord and probably won't. I'd opt for us to make a Slack
channel because it's a significantly better App.

**Comment by RealPoke** [comment]
Ehm, why close this?

**Pull request closed without merging**
